# Generated by Django 4.2.15 on 2025-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpl', '0002_paymentplan_merchant_paymentplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='user_email',
        ),
    ]
