# Generated by Django 4.2.15 on 2025-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpl', '0003_remove_paymentplan_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
