# Generated by Django 4.2.15 on 2025-04-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpl', '0004_installment_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('paid', 'paid')], default='active', max_length=20),
        ),
    ]
